apiVersion: v1
kind: Service
metadata:
  labels:
    app: miner-backend-service
  name: miner-backend-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: miner-monero-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: miner-frontend-service
  name: miner-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: miner-monero-frontend
